# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as environment variables. Some entries
# may override variables set by alacritty itself.
env:
  # This value is used to set the `$TERM` environment variable for each instance of
  # Alacritty. If it is not present, alacritty will check the local terminfo database and
  # use `alacritty` if it is available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  dimensions:
    columns: 0
    lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  position:
    x: 0
    y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  decorations: full

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 3000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 0

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: false

# Spaces per Tab (changes require restart)
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
tabspaces: 8

# Font configuration (changes require restart)
font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular
  bold:
    family: RobotoMono Nerd Font
    style: Bold
  italic:
    family: RobotoMono Nerd Font
    style: Italic
  bold_italic:
    family: RobotoMono Nerd Font
    style: Bold Italic
  size: 10.0
  # Offset is the extra space around each character. `offset.y` can be thought of as
  # modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with the
  # default being at the bottom. Increasing `x` moves the glyph to the right, increasing
  # `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x232627'
    foreground: '0xd7d8d8'
  # Set the colors for highlighting text.
  selection:
    text: '0x080808'
    background: '0x7391b7'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xaf5f5f'
    green:   '0x17a262'
    yellow:  '0xdfaf5f'
    blue:    '0x1d99f3'
    magenta: '0x9b59b6'
    cyan:    '0x1cdc9a'
    white:   '0xeeeeee'

  # Bright colors
  bright:
    black:   '0xa8a8a8'
    red:     '0xf2201f'
    green:   '0x19cb00'
    yellow:  '0xdfaf5f'
    blue:    '0x1d99f3'
    magenta: '0x9b59b6'
    cyan:    '0x1cdc9a'
    white:   '0xeeeeee'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x303030'
    red:     '0xb25e6c'
    green:   '0x87ffaf'
    yellow:  '0xdfaf5f'
    blue:    '0x57b1f6'
    magenta: '0x8787d7'
    cyan:    '0x00ffd7'
    white:   '0xeeeeee'

# Specifying a `duration` of `0` will disable the visual bell.
visual_bell:
  animation: EaseOutExpo
  duration: 0
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
dynamic_title: true

cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  # Render the cursor style as a hollow box when unfocused.
  unfocused_hollow: true

# Live config reload.
live_config_reload: true

# Shell
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux) user login shell
#   - (Windows) powershell
shell:
  program: /bin/bash
  args:
    - --login

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time alacritty should wait
  # for accepting multiple clicks as one double or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # Hide the cursor when typing.
  hide_when_typing: false

  url:
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    launcher:
      program: xdg-open

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  # (Windows/Linux only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
#   - ScrollLineUp
#   - ScrollLineDown

  # (macOS only)
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Add,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: V,      mods: Command,         action: Paste            }
  - { key: C,      mods: Command,         action: Copy             }



#debug:
  # Display the time it takes to redraw each frame.
  #render_timer: false

  # Keep the log file after quitting Alacritty.
  #persistent_logging: false

  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  #log_level: Warn

  # Print all received window events.
  #print_events: false

  # Record all characters and escape sequences as test data.
  #ref_test: false
