## Flashfocus config file

# Opacity of window during flash.
flash-opacity: 0.6

# Windows are restored to this opacity value at the end of a flash.
default-opacity: 1

# Length of flash in milliseconds.
time: 100

# If true, flashes are not faded out. This will improve performance but flashes
# won't be smooth.
simple: false

# Number of animation frames in a flash.
ntimepoints: 10

# Set this to False if you don't want windows to flash on focus.
flash-on-focus: true

# Always flash windows if they are the only window on the desktop.
flash-lone-windows: 'always'

rules:
  - window-class: (?i)firefox*
    flash-opacity: 0.5
  - window-class: (?i)chrom(e|ium)
    flash-opacity: 0.5
